version: 0.2  
phases:
  build:
    commands:
        - echo "here we start"
        - docker login -u AWS -p $(aws ecr-public get-login-password --region us-east-1) public.ecr.aws
        - docker build -t conduit-frontend .
        - docker tag conduit-frontend:latest public.ecr.aws/r3e8t5p1/conduit-frontend:latest
        - docker tag conduit-frontend:latest public.ecr.aws/r3e8t5p1/conduit-frontend:${CODEBUILD_BUILD_NUMBER}
        - docker push public.ecr.aws/r3e8t5p1/conduit-frontend:latest
        - docker push public.ecr.aws/r3e8t5p1/conduit-frontend:${CODEBUILD_BUILD_NUMBER}
        - aws eks --region us-east-1 update-kubeconfig --name production-eks-cluster
        - aws sts get-caller-identity
        - kubectl version
        - kubectl -n conduit set image deploy/conduit-frontend conduit-frontend=conduit-frontend:${CODEBUILD_BUILD_NUMBER}
